
INSERT INTO SINGER(FIRST_NAME, LAST_NAME, BIRTH_DATE)
  VALUES ('Siwoo', 'Kim', '1989-03-04');
INSERT INTO SINGER(FIRST_NAME, LAST_NAME, BIRTH_DATE)
  VALUES ('Eric', 'Clapton', '1945-03-30');
INSERT INTO SINGER(FIRST_NAME, LAST_NAME, BIRTH_DATE)
  VALUES ('John', 'Bulter', '1975-04-01');

INSERT INTO ALBUM (SINGER_ID, TITLE, RELEASE_DATE)
VALUES (5, 'The Search For Everything', '2017-01-20');

INSERT INTO ALBUM (SINGER_ID, TITLE, RELEASE_DATE)
VALUES (6, 'Battle Studies', '2009-11-17');

INSERT INTO ALBUM (SINGER_ID, TITLE, RELEASE_DATE)
VALUES (7, 'From The Candle', '1994-09-13');
